experiment: 'RLFN'

seed: 20230601

epochs: 200
batch_size: 8
workers: 16
train_parts: 1
valid_parts: 1
valid_start: 150
save_start: 150


optimizer: Adadelta
lr: 1
lr_decay: cosine
step_ratio: 10
step_decay: 5
eps: 1e-6
weight_decay: 1e-4
beta: 0.9

dropout: True
dropout_ratio: 0.5
relu: True
gradient: 100
gradient_clip: True
use_label_mask: False

train_image_path: './datasets/train_images.pkl'
train_label_path: './datasets/train_labels.txt'
eval_image_path: './datasets/14_test_images.pkl'
eval_label_path: './datasets/14_test_labels.txt'
word_path: './datasets/words_dict.txt'
token_path: './datasets/token.json'

densenet:
  ratio: 16
  growthRate: 24
  reduction: 0.5
  bottleneck: True
  use_dropout: True

encoder:
  input_channel: 1
  out_channel: 684

decoder:
  net: AttDecoder
  cell: 'GRU'
  input_size: 256
  hidden_size: 256

fusion:
  sizein1: 256
  sizein2: 768
  sizeout: 256

words_num: 111

attention:
  attention_dim: 512
  word_conv_kernel: 1

optimizer_save: False
finetune: False
checkpoint_dir: 'checkpoints'
checkpoint: './checkpoints/best_thin.pth'
log_dir: 'logs'
